# Generated by Django 4.0.4 on 2022-05-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_note_parent_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='parent_course',
        ),
    ]
