# Generated by Django 4.0.4 on 2022-05-06 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_remove_note_parent_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='parent_course',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.course'),
        ),
    ]
